"""Framework-independent EnergyPlus platform contracts for EcoLoop AI."""

from ecoloop_energyplus.application import SimulationResultAssembler, SimulationService
from ecoloop_energyplus.config.models import (
    EnergyPlusPlatformConfig,
    EnergyPlusSettings,
    OutputSettings,
    SimulationSettings,
)
from ecoloop_energyplus.domain.enums import SimulationArtifactKind, SimulationStatus
from ecoloop_energyplus.domain.exceptions import (
    EnergyPlusConfigurationError,
    EnergyPlusError,
    EnergyPlusNotInstalled,
    EnergyPlusVersionUnsupported,
    InvalidIDF,
    InvalidSimulationInput,
    InvalidWeatherFile,
    OutputParseError,
    SimulationError,
    SimulationFailed,
    SimulationTimeout,
)
from ecoloop_energyplus.domain.models import (
    ComfortMetrics,
    EnergyMetrics,
    HVACMetrics,
    Simulation,
    SimulationArtifact,
    SimulationMetadata,
    SimulationMetrics,
    SimulationMetricValue,
    SimulationResult,
    SimulationSpec,
    SummaryEntry,
    SummaryTable,
    WeatherMetrics,
    ZoneMetrics,
)
from ecoloop_energyplus.infrastructure.execution import (
    EnergyPlusCommandBuilder,
    EnergyPlusRunner,
    ExecutionCommand,
    ExecutionResult,
    ExecutionTimeout,
    ProcessManager,
)
from ecoloop_energyplus.infrastructure.locator import (
    CompositeEnergyPlusLocator,
    EnergyPlusCandidateSource,
    EnergyPlusInstallationCandidate,
    EnergyPlusLocatorResult,
    EnergyPlusPlatform,
    FilesystemProbe,
    VersionProbe,
    VersionProbeResult,
)
from ecoloop_energyplus.infrastructure.output import (
    ArtifactManifest,
    CleanupManager,
    CleanupResult,
    OutputManager,
    RunDirectory,
)
from ecoloop_energyplus.infrastructure.validation import (
    InputValidator,
    PathValidator,
    StartupValidator,
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
)
from ecoloop_energyplus.parser.csv import CsvColumn, CsvParser, CsvParseResult
from ecoloop_energyplus.parser.err import (
    ErrDiagnostic,
    ErrDiagnosticsReport,
    ErrParser,
    ErrSeverity,
)
from ecoloop_energyplus.parser.eso import (
    EsoParser,
    EsoParseResult,
    EsoSeries,
    EsoVariableDefinition,
)
from ecoloop_energyplus.parser.sql import SqlParser, SqlParseResult
from ecoloop_energyplus.parser.summary import SummaryParser, SummaryParseResult

__all__ = [
    "ArtifactManifest",
    "CleanupManager",
    "CleanupResult",
    "ComfortMetrics",
    "CompositeEnergyPlusLocator",
    "CsvColumn",
    "CsvParseResult",
    "CsvParser",
    "EnergyMetrics",
    "EnergyPlusCandidateSource",
    "EnergyPlusCommandBuilder",
    "EnergyPlusConfigurationError",
    "EnergyPlusError",
    "EnergyPlusInstallationCandidate",
    "EnergyPlusLocatorResult",
    "EnergyPlusNotInstalled",
    "EnergyPlusPlatform",
    "EnergyPlusPlatformConfig",
    "EnergyPlusRunner",
    "EnergyPlusSettings",
    "EnergyPlusVersionUnsupported",
    "ErrDiagnostic",
    "ErrDiagnosticsReport",
    "ErrParser",
    "ErrSeverity",
    "EsoParseResult",
    "EsoParser",
    "EsoSeries",
    "EsoVariableDefinition",
    "ExecutionCommand",
    "ExecutionResult",
    "ExecutionTimeout",
    "FilesystemProbe",
    "HVACMetrics",
    "InputValidator",
    "InvalidIDF",
    "InvalidSimulationInput",
    "InvalidWeatherFile",
    "OutputManager",
    "OutputParseError",
    "OutputSettings",
    "PathValidator",
    "ProcessManager",
    "RunDirectory",
    "Simulation",
    "SimulationArtifact",
    "SimulationArtifactKind",
    "SimulationError",
    "SimulationFailed",
    "SimulationMetadata",
    "SimulationMetricValue",
    "SimulationMetrics",
    "SimulationResult",
    "SimulationResultAssembler",
    "SimulationService",
    "SimulationSettings",
    "SimulationSpec",
    "SimulationStatus",
    "SimulationTimeout",
    "SqlParseResult",
    "SqlParser",
    "StartupValidator",
    "SummaryEntry",
    "SummaryParseResult",
    "SummaryParser",
    "SummaryTable",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSeverity",
    "VersionProbe",
    "VersionProbeResult",
    "WeatherMetrics",
    "ZoneMetrics",
    "__version__",
]

__version__ = "0.1.0"
