"""Optimization engine package for EcoLoop AI."""

from ecoloop_ai.optimization.config import (
    OptimizationConfig,
    OptimizationConvergenceSettings,
    OptimizationIterationSettings,
    OptimizationObservabilitySettings,
    OptimizationReasoningSettings,
    OptimizationSafetySettings,
)
from ecoloop_ai.optimization.constraints import (
    ConstraintEvaluation,
    ConstraintEvaluator,
    ConstraintSeverity,
    ConstraintStatus,
    OptimizationConstraint,
)
from ecoloop_ai.optimization.convergence import (
    ConvergenceAssessment,
    ConvergenceReason,
)
from ecoloop_ai.optimization.decision_trace import (
    DecisionStage,
    DecisionTraceEntry,
)
from ecoloop_ai.optimization.evaluator import (
    CandidateEvaluation,
    EvaluationStatus,
)
from ecoloop_ai.optimization.exceptions import (
    GoalInterpretationError,
    HypothesisGenerationError,
    ObjectiveResolutionError,
    OptimizationConfigurationError,
    OptimizationError,
    OptimizationStateError,
    OptimizationValidationError,
    OptimizationWorkflowError,
    StrategyResolutionError,
)
from ecoloop_ai.optimization.explainability import ExplainabilityRecord
from ecoloop_ai.optimization.goal_interpreter import GoalInterpreter
from ecoloop_ai.optimization.history import OptimizationHistoryEntry
from ecoloop_ai.optimization.hypothesis import (
    EngineeringHypothesis,
    HypothesisCategory,
    HypothesisEngine,
    HypothesisEvaluation,
    ImpactDirection,
    ImpactEstimate,
    ImpactMagnitude,
    RiskAssessment,
    RiskLevel,
)
from ecoloop_ai.optimization.metrics import (
    OptimizationMetricSnapshot,
    OptimizationMetricTrend,
    resolve_metric_unit,
    resolve_metric_value,
)
from ecoloop_ai.optimization.models import (
    BuildingMetadata,
    CandidateStatus,
    DecisionInput,
    DecisionSummary,
    GoalInterpretation,
    ObjectiveEvaluation,
    OptimizationCandidate,
    OptimizationRequest,
    OptimizationResult,
    OptimizationSession,
    OptimizationStatus,
    StrategyDecision,
    WeatherMetadata,
)
from ecoloop_ai.optimization.objectives import (
    BaseObjective,
    CarbonObjective,
    ComfortObjective,
    CompositeObjective,
    CoolingObjective,
    CostObjective,
    CustomObjective,
    EnergyObjective,
    HeatingObjective,
    HVACObjective,
    LightingObjective,
    ObjectiveContract,
    ObjectivePriority,
    ObjectiveRegistry,
    OptimizationDirection,
    OptimizationGoal,
    OptimizationObjective,
    OptimizationObjectiveKind,
    PeakDemandObjective,
    VentilationObjective,
    default_direction,
    default_metric_name,
    objective_priority_weight,
)
from ecoloop_ai.optimization.optimizer import OptimizationEngine
from ecoloop_ai.optimization.planner import (
    OptimizationPlan,
    OptimizationPlanner,
    OptimizationPlanStep,
)
from ecoloop_ai.optimization.recommendation import (
    OptimizationRecommendation,
    RecommendationPriority,
)
from ecoloop_ai.optimization.report import OptimizationOutcomeReport
from ecoloop_ai.optimization.risk import RiskAssessor
from ecoloop_ai.optimization.rollback import RollbackPlan
from ecoloop_ai.optimization.scoring import (
    CarbonScore,
    ComfortScore,
    CompositeScore,
    CostScore,
    EnergyScore,
    NormalizedScore,
    PeakDemandScore,
    ScoreDimension,
    clamp_score,
    generic_score,
    weighted_average,
)
from ecoloop_ai.optimization.strategies import (
    AIGuidedStrategy,
    GreedyStrategy,
    HillClimbingStrategy,
    OptimizationAggressiveness,
    OptimizationStrategyKind,
    OptimizationStrategyProfile,
    RandomExplorationStrategy,
    RiskTolerance,
    RuleBasedStrategy,
    StrategyContract,
    StrategyRegistry,
)
from ecoloop_ai.optimization.workflow import OptimizationWorkflow

__all__ = [
    "AIGuidedStrategy",
    "BaseObjective",
    "BuildingMetadata",
    "CandidateEvaluation",
    "CandidateStatus",
    "CarbonObjective",
    "CarbonScore",
    "ComfortObjective",
    "ComfortScore",
    "CompositeObjective",
    "CompositeScore",
    "ConstraintEvaluation",
    "ConstraintEvaluator",
    "ConstraintSeverity",
    "ConstraintStatus",
    "ConvergenceAssessment",
    "ConvergenceReason",
    "CoolingObjective",
    "CostObjective",
    "CostScore",
    "CustomObjective",
    "DecisionInput",
    "DecisionStage",
    "DecisionSummary",
    "DecisionTraceEntry",
    "EnergyObjective",
    "EnergyScore",
    "EngineeringHypothesis",
    "EvaluationStatus",
    "ExplainabilityRecord",
    "GoalInterpretation",
    "GoalInterpretationError",
    "GoalInterpreter",
    "GreedyStrategy",
    "HVACObjective",
    "HeatingObjective",
    "HillClimbingStrategy",
    "HypothesisCategory",
    "HypothesisEngine",
    "HypothesisEvaluation",
    "HypothesisGenerationError",
    "ImpactDirection",
    "ImpactEstimate",
    "ImpactMagnitude",
    "LightingObjective",
    "NormalizedScore",
    "ObjectiveContract",
    "ObjectiveEvaluation",
    "ObjectivePriority",
    "ObjectiveRegistry",
    "ObjectiveResolutionError",
    "OptimizationAggressiveness",
    "OptimizationCandidate",
    "OptimizationConfig",
    "OptimizationConfigurationError",
    "OptimizationConstraint",
    "OptimizationConvergenceSettings",
    "OptimizationDirection",
    "OptimizationEngine",
    "OptimizationError",
    "OptimizationGoal",
    "OptimizationHistoryEntry",
    "OptimizationIterationSettings",
    "OptimizationMetricSnapshot",
    "OptimizationMetricTrend",
    "OptimizationObjective",
    "OptimizationObjectiveKind",
    "OptimizationObservabilitySettings",
    "OptimizationOutcomeReport",
    "OptimizationPlan",
    "OptimizationPlanStep",
    "OptimizationPlanner",
    "OptimizationReasoningSettings",
    "OptimizationRecommendation",
    "OptimizationRequest",
    "OptimizationResult",
    "OptimizationSafetySettings",
    "OptimizationSession",
    "OptimizationStateError",
    "OptimizationStatus",
    "OptimizationStrategyKind",
    "OptimizationStrategyProfile",
    "OptimizationValidationError",
    "OptimizationWorkflow",
    "OptimizationWorkflowError",
    "PeakDemandObjective",
    "PeakDemandScore",
    "RandomExplorationStrategy",
    "RecommendationPriority",
    "RiskAssessment",
    "RiskAssessor",
    "RiskLevel",
    "RiskTolerance",
    "RollbackPlan",
    "RuleBasedStrategy",
    "ScoreDimension",
    "StrategyContract",
    "StrategyDecision",
    "StrategyRegistry",
    "StrategyResolutionError",
    "VentilationObjective",
    "WeatherMetadata",
    "clamp_score",
    "default_direction",
    "default_metric_name",
    "generic_score",
    "objective_priority_weight",
    "resolve_metric_unit",
    "resolve_metric_value",
    "weighted_average",
]
