"""Domain models and exceptions for the EnergyPlus platform package."""

from ecoloop_energyplus.domain.enums import SimulationArtifactKind, SimulationStatus
from ecoloop_energyplus.domain.exceptions import (
    EnergyPlusConfigurationError,
    EnergyPlusError,
    EnergyPlusNotInstalled,
    EnergyPlusVersionUnsupported,
    InvalidIDF,
    InvalidSimulationInput,
    InvalidWeatherFile,
    OutputParseError,
    SimulationError,
    SimulationFailed,
    SimulationTimeout,
)
from ecoloop_energyplus.domain.models import (
    ComfortMetrics,
    EnergyMetrics,
    HVACMetrics,
    Simulation,
    SimulationArtifact,
    SimulationMetadata,
    SimulationMetrics,
    SimulationMetricValue,
    SimulationResult,
    SimulationSpec,
    SummaryEntry,
    SummaryTable,
    WeatherMetrics,
    ZoneMetrics,
)

__all__ = [
    "ComfortMetrics",
    "EnergyMetrics",
    "EnergyPlusConfigurationError",
    "EnergyPlusError",
    "EnergyPlusNotInstalled",
    "EnergyPlusVersionUnsupported",
    "HVACMetrics",
    "InvalidIDF",
    "InvalidSimulationInput",
    "InvalidWeatherFile",
    "OutputParseError",
    "Simulation",
    "SimulationArtifact",
    "SimulationArtifactKind",
    "SimulationError",
    "SimulationFailed",
    "SimulationMetadata",
    "SimulationMetricValue",
    "SimulationMetrics",
    "SimulationResult",
    "SimulationSpec",
    "SimulationStatus",
    "SimulationTimeout",
    "SummaryEntry",
    "SummaryTable",
    "WeatherMetrics",
    "ZoneMetrics",
]
